SELECT FIRST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 50
ORDER BY SALARY DESC;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 20, 30)
GROUP BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE SALARY > 8000;

SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;