CREATE TABLE JOGADOR
( 
    ID_JOGADOR NUMBER(10,0) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    POSICAO VARCHAR2(100),
    BI VARCHAR2(100),
    CONSTRAINT PK_JOGADOR PRIMARY KEY (ID_JOGADOR)
);

CREATE TABLE CONTRATADO
(
    ID_JOGADOR NUMBER(10,0) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    CONSTRAINT PK_CONTRATADO PRIMARY KEY (ID_JOGADOR, DATA_INICIO),
    CONSTRAINT FK_CONTRATADO_REF_JOGADOR FOREIGN KEY (ID_JOGADOR) 
        REFERENCES JOGADOR(ID_JOGADOR),
    CONSTRAINT CK_CONTRATADO_DATA_FIM CHECK (DATA_FIM > DATA_INICIO)
);

--Primary Key (JOGADOR)
--→ Identifica unicamente cada jogador.

--Primary Key composta (CONTRATADO)
--→ Garante que um jogador não tenha dois contratos iniciando na mesma data.

--Foreign Key (CONTRATADO → JOGADOR)
--→ Garante que todo contrato esteja ligado a um jogador existente.

ALTER TABLE JOGADOR RENAME TO JOGADORES;

ALTER TABLE JOGADORES RENAME TO JOGADOR;

ALTER TABLE JOGADOR ADD APELIDO VARCHAR2(30);

DESC JOGADOR;

ALTER TABLE JOGADOR MODIFY POSICAO NUMBER(5,0);

ALTER TABLE JOGADOR RENAME COLUMN APELIDO TO NICKNAME;

DESC JOGADOR;

ALTER TABLE JOGADOR DROP COLUMN BI CASCADE CONSTRAINTS;

DESC JOGADOR;

ALTER TABLE CONTRATADO DROP CONSTRAINT FK_CONTRATADO_REF_JOGADOR;

DROP TABLE JOGADOR;

ALTER TABLE CONTRATADO 
    ADD CONSTRAINT FK_CONTRATADO_REF_JOGADOR FOREIGN KEY (ID_JOGADOR) 
    REFERENCES JOGADOR(ID_JOGADOR);

ALTER TABLE CONTRATADO
    DISABLE CONSTRAINT FK_CONTRATADO_REF_JOGADOR;

ALTER TABLE CONTRATADO
    ENABLE CONSTRAINT FK_CONTRATADO_REF_JOGADOR;

/*
🧱 O que é uma CONSTRAINT?

CONSTRAINT é uma regra que você impõe ao banco de dados para garantir a integridade dos dados.

👉 Em outras palavras:

é o banco dizendo “esses dados só entram se respeitarem essas regras”.

Essas regras evitam:

Dados duplicados

Valores inválidos

Relacionamentos quebrados

Registros sem sentido no mundo real
*/

